-- Generated by Oracle SQL Developer Data Modeler 4.1.2.895
--   at:        2015-11-30 19:39:01 GET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
--  Author: Nikoloz Gochiashvili
--  Email: ngochiashvili@gmail.com




CREATE TABLE Customer
  (
    customer_id      INTEGER NOT NULL ,
    customer_name    VARCHAR2 (20 CHAR) ,
    customer_address VARCHAR2 (200 CHAR) ,
    other_details    VARCHAR2 (200)
  ) ;

CREATE TABLE "Date"
  (
    day_number   INTEGER NOT NULL ,
    day_date     TIMESTAMP (0) NOT NULL ,
    week_number  NUMBER ,
    month_number INTEGER ,
    year_number  INTEGER
  ) ;

CREATE TABLE Fact
  (
    fact_id                NUMBER NOT NULL ,
    sales_amount           NUMBER (10,10) ,
    sales_volume           NUMBER ,
    other_sales_details    VARCHAR2 (200 CHAR) ,  //Remove
    Product_product_code   VARCHAR2 (200 CHAR) NOT NULL ,
    Date_day_number        INTEGER NOT NULL ,	//Only this
    Date_day_date          TIMESTAMP (0) NOT NULL , //Remove
    Customer_customer_id   INTEGER NOT NULL ,
    Geography_Geography_ID NUMBER NOT NULL
  ) ;

CREATE TABLE Geography
  (
    geographic_area      VARCHAR2 (20 CHAR) ,
    geographic_area_name VARCHAR2 (200 CHAR) ,
    region               VARCHAR2 (200 CHAR) ,
    country              VARCHAR2 (200 CHAR) ,
    other_region_details VARCHAR2 (1000 CHAR) ,
    Geography_ID         NUMBER NOT NULL
  ) ;

CREATE TABLE Product
  (
    product_code          VARCHAR2 (200 CHAR) NOT NULL ,
    product_name          VARCHAR2 (200) ,
    product_description   VARCHAR2 (1000 CHAR) ,
    other_product_details VARCHAR2 (1000)
  ) ;
//Where are primary keys for tables??????????????????
ALTER TABLE Fact ADD CONSTRAINT Fact_Customer_FK FOREIGN KEY ( Customer_customer_id ) REFERENCES Customer ( customer_id ) ;

ALTER TABLE Fact ADD CONSTRAINT Fact_Date_FK FOREIGN KEY ( Date_day_number, Date_day_date ) REFERENCES "Date" ( day_number, day_date ) ;

ALTER TABLE Fact ADD CONSTRAINT Fact_Geography_FK FOREIGN KEY ( Geography_Geography_ID ) REFERENCES Geography ( Geography_ID ) ;

ALTER TABLE Fact ADD CONSTRAINT Fact_Product_FK FOREIGN KEY ( Product_product_code ) REFERENCES Product ( product_code ) ;

CREATE SEQUENCE Geography_Geography_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Geography_Geography_ID_TRG BEFORE
  INSERT ON Geography FOR EACH ROW WHEN (NEW.Geography_ID IS NULL) BEGIN :NEW.Geography_ID := Geography_Geography_ID_SEQ.NEXTVAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
